#!/usr/bin/env bash
# Create bash script to run Wine application in given environment
# shellcheck disable=SC2016
# shellcheck disable=SC2086

# Usage
function usage { cat << DONE; }
Usage:
  $(basename "${0}") <Windows .exe> <Wine _env> <script name>

Example:
  $(basename "${0}") ~/Windows/myapp.exe ~/myapp_env ~/myapp.sh

$(basename "${0}") with no arguments runs in interactive mode.

DONE

case "${1}" in
  h|help|-h|-help|--help) usage; exit 0;;
esac
if test ${#} -gt 3; then
  usage; exit 1
fi

# Set Windows .exe file
EXE="${1}"
test -z "${EXE}" && read -rep '.exe file: ' EXE

# Allow ~ and '' -- should make a function for this
EXE="${EXE//"~"/"$HOME"}"
test "$(echo "${EXE}" | cut -c -1)" == "'" &&\
  test "$(echo "${EXE}" | rev | cut -c -1)" == "'" &&\
  EXE="$(echo "${EXE}" | cut -c 2- | rev | cut -c 2- | rev)"

EXE_DIR="$(cd "$(dirname "${EXE}")" && pwd)"
EXE="$(basename "${EXE}")"

# Set Wine environment file
ENV="${2}"
if test -z "${ENV}"; then
  read -rep 'Wine _env: ' ENV
fi

# Allow ~ and ''
ENV="${ENV//"~"/"$HOME"}"
test "$(echo "${ENV}" | cut -c -1)" == "'" &&\
  test "$(echo "${ENV}" | rev | cut -c -1)" == "'" &&\
  ENV="$(echo "${ENV}" | cut -c 2- | rev | cut -c 2- | rev)"

ENV_DIR="$(cd "$(dirname "${ENV}")" && pwd)"
ENV="$(basename "${ENV}")"
ENV="${ENV_DIR}/${ENV}"

# Set script name
SCRIPT="${3}"
test -z "${SCRIPT}" && SCRIPT='run.sh'
if test -f "${SCRIPT}"; then
  echo 'ERROR: "'${SCRIPT}'" already exists.'
  exit 1
fi
SCRIPT_DIR="$(cd "$(dirname "${SCRIPT}")" && pwd)"

# Make ENV and EXE_DIR relative to SCRIPT_DIR
ENV="${ENV//"${SCRIPT_DIR}"/.}"
EXE_DIR="${EXE_DIR//"${SCRIPT_DIR}"/.}"

# Write script template
echo 'Creating script for Wine application...'
echo \
'#!/bin/bash
# Wine launch script for '"$(basename "${EXE}")"'
# vvv  Remove this line  vvv
echo "Edit this script before running."; exit

# Change to script'"'s"' directory
cd "$(cd "${0%/*}" && pwd)" || exit 1

# Set Wine environment
source "'"${ENV}"'"

# Set application .exe to run
EXE="'"${EXE}"'"

# Run application
cd "'"${EXE_DIR}"'" || exit 1
wine "${EXE}" "${@}"' > "${SCRIPT}"

chmod +x "${SCRIPT}"
echo '  Script written to "'${SCRIPT_DIR}/${SCRIPT}'"

Edit this script before running.
'
